### ISSUE TITLE
I want to play the specified frame how to achieve?

### ISSUE THREAD

**Issue by likaia** [davidmz/apng-js#25]

**Comment by davidmz** [comment]
You can create player as usual and use it renderNextFrame() method to render all frames from 0 to desired number.

**Comment by likaia** [comment]
The renderNextFrame method will read the previous frame, and I want to jump directly to a certain frame to get the animation of this frame

**Comment by davidmz** [comment]
In general, you cannot do this because APNG frames are not complete images. They are "patches" that correct the images rendered in the previous frame. Only the first frame is independent, the second and subsequent frames require something already rendered on the canvas.

But you free to select specific Frame object and call it's createImage() method to generate imageElement for this frame. But it probably won't be a complete picture.

**Comment by likaia** [comment]
Haha, i got it.

When I initialized the player, I preloaded all the frames once and then put them into the snapshot.
When jumping to a specified frame, I took the image of that frame from the snapshot and rendered it to the canvas.

Can I add your contact information?
Let's talk together

**Comment by likaia** [comment]
solved
