### ISSUE TITLE
help：I have an APNG image, which will be truncated a lot when placed in your demo

### ISSUE THREAD

**Issue by sunset-horizon** [davidmz/apng-js#36]
![image](https://github.com/davidmz/apng-js/assets/35354625/ac5be8ad-1bcc-4a8b-923d-9e4c0bc8d3f8)
![angry](https://github.com/davidmz/apng-js/assets/35354625/cc246b03-f09b-4b01-8650-af80a1a39b91)

As shown in the figure, my APNG size was truncated incorrectly, which resulted in a strange display when my project was used. It is speculated that there was some problem with the calculation of high truncation, but I did not see it, so I came to seek your help

**Comment by davidmz** [comment]
Hi! I don't actually see any problems with this file. The player on the demo page displays it correctly, and the third frame is indeed that size.

Could you describe what problems you are seeing in your project?

**Comment by sunset-horizon** [comment]
Thank you for your reply. The current issue I am facing is playing with this image. In the third frame, due to the sudden flattening of the image, the effect looks strange. At first, I thought it was a code parsing problem, but after seeing your reply, I realized that there was a problem with this image. However, I am not sure why the demonstration animation does not display the problem

**Comment by davidmz** [comment]
There is no problem with the image :) The APNG format is simple, but has some tricks. Each frame has, besides the image itself, two fields: 'dispose_op' and 'blend_op' (https://wiki.mozilla.org/APNG_Specification). In your APNG, frame1's dispose_op is 2 (APNG_DISPOSE_OP_PREVIOUS). This means that after showing this frame, the player must forget about it and apply the next frame to the _previous_ frame state.

This is the full player sequence:
1. Show frame0.
2. Show frame1 on top of the current image
3. Reset the current image to the state before step 1 and show frame 2 on top.
4. Show frame3 on top of the current image.
5. Repeat from step 1.

So the "flatten" image of frame2 is actually applied to the image of frame0 instead of frame1.

**Comment by sunset-horizon** [comment]
I have used your method and indeed solved my problem. Thank you very much and wish you a happy life
